### ISSUE TITLE
Inconsistent behavior when using query reflection api

### ISSUE THREAD

**Issue by clusc** [aerospike/aerospike-client-go#188] opened 2017-04-08 17:54 UTC
Hi,

We observed an inconsistent behavior when submitting querying using the reflection api. The result sometime comes back and sometime doesn't, when we are issuing the same query over and over again. Please see the following gist for detail:
https://gist.github.com/clusc/e9705ff8f78b19321a34781445e3fd3e

Server: CE 3.12
Client: v1.26.0

Thanks

**Comment by khaf** [comment] 2017-04-08 17:56
Hi Eric, how many nodes do you have? And how many records?

**Comment by clusc** [comment] 2017-04-08 17:58
3 nodes. The particular set only contains ~250 records(primary). Each record is pretty big though.

**Comment by khaf** [comment] 2017-04-12 13:49
I still can't reproduce this. Is it possible to share (a sanitized copy of) the data in that set privately?

**Comment by clusc** [comment] 2017-04-12 15:20
You can try with the mapzen data [here](http://s3.amazonaws.com/osm-polygons.mapzen.com/planet_geojson.tgz). The issue seems to related to the size of the polygon. Try with admin_level_2(country level) from that set to see if you can reproduce the issue.

**Comment by khaf** [comment] 2017-06-22 11:42
This seems to be a server-side issue, which I believe was followed up by support. I'm going to go ahead and close this issue. Feel free to reopen or file new issues.

**Closed** 2017-06-22 11:41 UTC
