### ISSUE TITLE
Data race in rand.Int64()

### ISSUE THREAD

**Issue by ofw** [aerospike/aerospike-client-go#253] opened 2019-01-16 10:50 UTC
Caught a race condition running my program built with `-race` flag. May be this behaviour is intentional and there is nothing to worry about but it is up to you.

```sh
WARNING: DATA RACE
Read at 0x00c0001b4268 by goroutine 980:
  github.com/aerospike/aerospike-client-go/types/rand.Int64()
      /src/github.com/aerospike/aerospike-client-go/types/rand/xor_shift128.go:59 +0xd7
  github.com/aerospike/aerospike-client-go.(*baseMultiCommand).putConnection()
      /src/github.com/aerospike/aerospike-client-go/batch_command.go:90 +0x33
  github.com/aerospike/aerospike-client-go.(*batchCommandGet).putConnection()
      <autogenerated>:1 +0x4d
  github.com/aerospike/aerospike-client-go.(*baseCommand).execute()
      /src/github.com/aerospike/aerospike-client-go/command.go:1701 +0x12b9
  github.com/aerospike/aerospike-client-go.(*batchCommandGet).Execute()
      /src/github.com/aerospike/aerospike-client-go/batch_command_get.go:257 +0x50
  github.com/aerospike/aerospike-client-go.(*Client).batchExecute.func1()
      /src/github.com/aerospike/aerospike-client-go/client.go:1212 +0x75

Previous write at 0x00c0001b4268 by goroutine 1762:
  github.com/aerospike/aerospike-client-go/types/rand.Int64()
      /src/github.com/aerospike/aerospike-client-go/types/rand/xor_shift128.go:62 +0x109
  github.com/aerospike/aerospike-client-go.(*baseMultiCommand).getConnection()
      /src/github.com/aerospike/aerospike-client-go/batch_command.go:86 +0x55
  github.com/aerospike/aerospike-client-go.(*batchCommandGet).getConnection()
      <autogenerated>:1 +0x51
  github.com/aerospike/aerospike-client-go.(*baseCommand).execute()
      /src/github.com/aerospike/aerospike-client-go/command.go:1628 +0x41b
  github.com/aerospike/aerospike-client-go.(*batchCommandGet).Execute()
      /src/github.com/aerospike/aerospike-client-go/batch_command_get.go:257 +0x50
  github.com/aerospike/aerospike-client-go.(*Client).batchExecute.func1()
      /src/github.com/aerospike/aerospike-client-go/client.go:1212 +0x75
```

library version: `1.37.0`

**Comment by khaf** [comment] 2019-01-16 10:52
Thanks for your report. This is not really a bug and still works as intended, but I'll synchronize the access in the next release to remove the issue.

**Comment by khaf** [comment] 2019-03-19 11:38
Fixed in the latest version.

**Closed by khaf** 2019-03-19 11:38 UTC
