### ISSUE TITLE
Put() results in a Invalid node exception after CP update

### ISSUE THREAD

**Issue by tchiam** [aerospike/aerospike-client-go#229] opened 2018-04-18 20:46 UTC
Hi @khaf,

After https://github.com/aerospike/aerospike-client-go/commit/c4fa10e1a2c8f4d19f57d54c28b9c5fe0dac2fe6 , calling Put() with a client that is directly connected to a single node results in a Invalid node exception. This was working prior to this commit. Get() still works as expected and CP mode is not enabled. Is this expected behavior? Would it be possible to reenable the old behavior? The old behavior is extremely convenient when talking to a cluster in a separate network.

Thanks,
Chiam

**Comment by fmstephe** [comment] 2018-04-24 15:59
We are experiencing the same problem. Getting errors which print

```
"command execution timed out on client: Exceeded number of retries. See `Policy.MaxRetries`. (last error: Invalid node)"
```

in our CI build which connects to a single aerospike instance.

**Comment by khaf** [comment] 2018-04-24 17:40
Working on it...

**Comment by khaf** [comment] 2018-04-25 09:16
Can someone provide their config file? I can't reproduce this on my side on the configurations, git revisions and server versions I checked.

Are you encountering this problem while doing other transactions (like batch/query/scan/aggregation), or just by issuing `Put()` commands? Is it a `Put()`, or `PutBins()`?

What is your `ClientPolicy` and `WritePolicy`? Does the benchmark application released with the client ( you can find it in`github.com/aerospike/aerospike-client-go/tools/benchmark`) also exhibit this issue?

My run of the benchmark app shows the following output, without any errors or timeouts:

```
± go run tools/benchmark/benchmark.go -h vmu1604 -k 100000 -w I -L 5,2 -d
2018/04/25 10:10:12 Setting number of CPUs to use: 8
2018/04/25 10:10:12 benchmark.go:181: hosts:		vmu1604
2018/04/25 10:10:12 benchmark.go:182: port:		3000
2018/04/25 10:10:12 benchmark.go:183: namespace:		test
2018/04/25 10:10:12 benchmark.go:184: set:		testset
2018/04/25 10:10:12 benchmark.go:185: keys/records:	100000
2018/04/25 10:10:12 benchmark.go:186: object spec:	I, size: 0
2018/04/25 10:10:12 benchmark.go:187: random bin values	false
2018/04/25 10:10:12 benchmark.go:188: workload:		Initialize 100% of records
2018/04/25 10:10:12 benchmark.go:189: concurrency:	32
2018/04/25 10:10:12 benchmark.go:190: max throughput	unlimited
2018/04/25 10:10:12 benchmark.go:191: timeout		0 ms
2018/04/25 10:10:12 benchmark.go:192: max retries		2
2018/04/25 10:10:12 benchmark.go:193: debug:		true
2018/04/25 10:10:12 benchmark.go:194: latency:		2:5
2018/04/25 10:10:12 logger.go:95: No connections available; seeding...
2018/04/25 10:10:12 logger.go:95: Seeding the cluster. Seeds count: 1
2018/04/25 10:10:12 logger.go:88: Node Validator has 1 nodes and they are: [172.16.224.166:3000]
2018/04/25 10:10:12 logger.go:88: Adding node BB9C97CED290C00 (172.16.224.166:3000) to the cluster.
2018/04/25 10:10:12 logger.go:95: Node BB9C97CED290C00 partition generation -2 changed to 0
2018/04/25 10:10:12 logger.go:95: Tend finished. Live node count changes from 0 to 1
2018/04/25 10:10:12 logger.go:88: New cluster initialized and ready to be used...
2018/04/25 10:10:12 benchmark.go:137: Nodes Found: [BB9C97CED290C00]
2018/04/25 10:10:12 logger.go:95: Starting the cluster tend goroutine...
2018/04/25 10:10:13 benchmark.go:712: write(tps=45686 timeouts=0 errors=0 totalCount=45686) (malloc (KiB): 11174, GC pause(ms): 0)
2018/04/25 10:10:13 benchmark.go:731: 		Min(ms)	Avg(ms)	Max(ms)	|<=   2 ms	|>   2 ms	|>   4 ms	|>   8 ms	|>  16 ms	|>  32 ms
2018/04/25 10:10:13 benchmark.go:738: 	READ	0	0.000	0	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%
2018/04/25 10:10:13 benchmark.go:745: 	WRITE	0	0.188	14	|  45229/99.00%	|    457/1.00%	|     90/0.20%	|     16/0.04%	|      0/0.00%	|      0/0.00%
2018/04/25 10:10:14 benchmark.go:712: write(tps=48261 timeouts=0 errors=0 totalCount=93947) (malloc (KiB): 7275, GC pause(ms): 0)
2018/04/25 10:10:14 benchmark.go:731: 		Min(ms)	Avg(ms)	Max(ms)	|<=   2 ms	|>   2 ms	|>   4 ms	|>   8 ms	|>  16 ms	|>  32 ms
2018/04/25 10:10:14 benchmark.go:738: 	READ	0	0.000	0	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%
2018/04/25 10:10:14 benchmark.go:745: 	WRITE	0	0.183	9	|  47800/99.04%	|    461/0.96%	|     70/0.15%	|      5/0.01%	|      0/0.00%	|      0/0.00%
2018/04/25 10:10:14 benchmark.go:712: write(tps=6053 timeouts=0 errors=0 totalCount=100000) (malloc (KiB): 641, GC pause(ms): 0)
2018/04/25 10:10:14 benchmark.go:731: 		Min(ms)	Avg(ms)	Max(ms)	|<=   2 ms	|>   2 ms	|>   4 ms	|>   8 ms	|>  16 ms	|>  32 ms
2018/04/25 10:10:14 benchmark.go:738: 	READ	0	0.000	0	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%
2018/04/25 10:10:14 benchmark.go:745: 	WRITE	0	0.123	4	|   6037/99.72%	|     16/0.26%	|      0/0.00%	|      0/0.00%	|      0/0.00%	|      0/0.00%
```

**Comment by fmstephe** [comment] 2018-04-25 13:13
We have tracked it down to a specific method call. (It would be nice to be able to distinguish between all the different INVALID_NODE_ERRORs so they could be linked to their exact origin.)

We are seeing this for both `Write` and `Delete` commands. They both seem to fail in the same way.

### delete stack trace
```
runtime/debug.Stack(0x9de478, 0x1, 0x1)
/usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
.../github.com/aerospike/aerospike-client-go.(*Cluster).getMasterNode(0xc4200d4f00, 0xc420468908, 0x47d80d, 0xc42006b308, 0x0)
.../github.com/aerospike/aerospike-client-go/cluster.go:830 +0x492
.../github.com/aerospike/aerospike-client-go.(*deleteCommand).getNode(0xc4204688c0, 0xa5a440, 0xc4204688c0, 0x0, 0xbeb03c3e24fdfb73, 0x1ac6ccd).../github.com/aerospike/aerospike-client-go/delete_command.go:50 +0x38
.../github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc4204688c0, 0xa5a440, 0xc4204688c0, 0x9e1d00, 0x6, 0x67b)
.../github.com/aerospike/aerospike-client-go/command.go:1605 +0x18f
.../github.com/aerospike/aerospike-client-go.(*deleteCommand).Execute(0xc4204688c0, 0xc42014c680, 0xc42045c0c0)
.../github.com/aerospike/aerospike-client-go/delete_command.go:81 +0x43
.../github.com/aerospike/aerospike-client-go.(*Client).Delete(0xc4206d6000, 0xc42014c680, 0xc42045c0c0, 0x5, 0x8f3f60, 0xc420476310)
.../github.com/aerospike/aerospike-client-go/client.go:234 +0x71
```
### write stack trace
```
runtime/debug.Stack(0x9de478, 0x1, 0x1)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x22
.../github.com/aerospike/aerospike-client-go.(*Cluster).getMasterNode(0xc4200d4f00, 0xc420462318, 0x47d80d, 0xc42006b228, 0x0).../github.com/aerospike/aerospike-client-go/cluster.go:830 +0x492
.../github.com/aerospike/aerospike-client-go.(*writeCommand).getNode(0xc4204622d0, 0xa5a920, 0xc4204622d0, 0x0, 0xbeb03c3e25067fd5, 0x1b4f134)
.../github.com/aerospike/aerospike-client-go/write_command.go:61 +0x38
.../github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc4204622d0, 0xa5a920, 0xc4204622d0, 0x9e1d00, 0x6, 0x67b)
.../github.com/aerospike/aerospike-client-go/command.go:1605 +0x18f.../github.com/aerospike/aerospike-client-go.(*writeCommand).Execute(0xc4204622d0, 0xc42014c680, 0xc42045c480)
.../github.com/aerospike/aerospike-client-go/write_command.go:89 +0x43.../github.com/aerospike/aerospike-client-go.(*Client).PutBins(0xc4206d6000, 0xc42014c680, 0xc42045c480, 0xc4204764e0, 0x2, 0x2, 0xc42045c480, 0x0)
.../github.com/aerospike/aerospike-client-go/client.go:159 +0xa2
```

When it goes looking for the node [at](https://github.com/aerospike/aerospike-client-go/blob/v1.32.0/cluster.go#L799) it is always nil. If we look at all the nodes in `partitions.Replicas[0]` they are all `nil`, so there is no way to get a node from this partition map.

If we call `clstr.GetNodes()` it returns a single node so the config does know that there is a node but it is not making its way into the partition map where `getMasterNode` expects it to be.

I'll post the config for the cluster client shortly.

It's important to note that I added code to generate those stack traces and debug info etc. So the original source is not panicking.

**Comment by fmstephe** [comment] 2018-04-25 13:48
If we check the `partitionMap` on the node we have it also contains no nodes. So although the clusters partition map is being merged with the node the node itself looks like it has a bad partition map.

**Comment by khaf** [comment] 2018-04-25 14:47
Thanks for the help, this is a good progress. Can you check on [node.refreshPartitions()](https://github.com/aerospike/aerospike-client-go/blob/v1.32.0/node.go#L329) to see if the partition map from the partitions parser is coming back ok? If it's not, then we will have to find out which info command is being sent to the server to query the partition map. You can find that [here](https://github.com/aerospike/aerospike-client-go/blob/v1.32.0/partition_parser.go#L54)

This issue looks to be due to a partition map query from the server. To make sure the server is returning the partitions map, you can do:

```bash
$ asinfo -v "replicas-master"
$ asinfo -v "replicas"
$ asinfo -v "replicas-all"
```

`replicas-master` and `replicas-all` should always return the partition map.

**Comment by fmstephe** [comment] 2018-04-25 14:52
When we hit this [line](https://github.com/aerospike/aerospike-client-go/blob/v1.32.0/partition_parser.go#L66) Every namespace is just `AAAAAAAAAAAA...` which decodes to zeros and never gets picked up [here](https://github.com/aerospike/aerospike-client-go/blob/v1.32.0/partition_parser.go#L293).

I'm not sure which command is being used to get that. I'll check now.

**Comment by fmstephe** [comment] 2018-04-25 15:03
The command to update the config is [this](https://github.com/aerospike/aerospike-client-go/blob/v1.32.0/partition_parser.go#L54). The other two branches don't get hit.

**Comment by khaf** [comment] 2018-04-25 15:05
What is the output from issuing the following command?
```
asinfo -h <host> -v "replicas-master"
```

**Comment by fmstephe** [comment] 2018-04-25 15:05
I am not able to run those commands in our ci environment. Hopefully we can get the info we need just via debugging.

**Comment by khaf** [comment] 2018-04-25 15:08
then this is not a client issue. From what I can understand, the node in question cannot determine it is the master node for all partitions. As a result, it is returning 0 for everything.

This seems to be configuration related. I guess our support staff are more adept at answering these questions. If you can post a config, I will use other channels to find out why this is happening.

**Comment by fmstephe** [comment] 2018-04-25 15:09
But this environment works fine with client 1.31.0

**Comment by tchiam** [comment] 2018-04-25 23:08
Hi, my issue is caused by the same code path, but the issue isn't config but how we connect to the cluster.
`asinfo -h <host> -v "replicas-master"`
returns a partitions map that looks meaningful.

Let me try to explain our use case a little bit more and see if there is a possible work around. We run an Aerospike cluster in GKE, and sometimes we want to connect to it from a dev environment in a separate network, where we rely on port forwarding for connectivity. 

So prior to the getMasterNode() change, the partition map set up code fails because of network isolation, but we can connect via the random node (in our case this is the localhost:<forwarded port>. With the new change, the set up still fails, and the InvalidNode error is thrown.

So the behavior we were relying on has understandably been changed, but is there some other way of achieving what we are trying to do?

**Comment by khaf** [comment] 2018-04-26 10:05
@tchiam you may be able to use IpMap in the client Policy to achieve that goal. Let me know if that makes sense.

**Comment by tchiam** [comment] 2018-04-28 00:43
Can you provide a brief description of how the IpMap will loaded and used to build the partition map? I have trouble getting it to work, first it's not getting loaded because [https://github.com/aerospike/aerospike-client-go/blob/master/node_validator.go#L224] is turned on, and even after disabling it locally, the partition map building code doesn't seem to run.

**Comment by khaf** [comment] 2018-07-17 17:47
@tchiam Sorry it seems I missed your message on time. 

IpMap maps some IPs to others, so you can map the internal IP of the node to the external ones and the client will use those when it tries to connect to the node.

It seems that we have a new feature that may help you with your use case in the next version, in which server reports its external IPs.

**Comment by khaf** [comment] 2018-10-02 13:43
We now have support for load balancers, and the original issue of this ticket has been resolved. I'm closing this one. Feel free to open a new ticket for any issues you may encounter.

**Closed by khaf** 2018-10-02 13:43 UTC
