### ISSUE TITLE
Corrupted data when getting during scan

### ISSUE THREAD

**Issue by allenluce** [aerospike/aerospike-client-go#167] opened 2016-12-15 17:11 UTC
Doing several gets during a scan gives me all kinds of errors:

```
During scan: Invalid readBytes length: 1818846055
During scan: Invalid readBytes length: 1946157052
During scan: Invalid readBytes length: -5
During scan: Invalid readBytes length: -7
During scan: Error code (110) not available yet - please file an issue on github.
During scan: Error code (101) not available yet - please file an issue on github.
During scan: Error code (124) not available yet - please file an issue on github.
During scan: Generation error
During scan: EOF
```

This is from code like this:

```
  recordset, _ := AerospikeClient.ScanAll(nil, "dimensions", "headers")
  for res := range recordset.Results() {
    if res.Err != nil {
      fmt.Printf("During scan: %s\n", res.Err.Error())
      continue
    }
    sum := 0
    for i := 0; i < res.Record.Bins["itemcount"].(int); i++ {
      key := fmt.Sprintf("item%d", i)
      itemKey, _ := aerospike.NewKey("dimensions", "items", key)
      rec, _ := AerospikeClient.Get(nil, itemKey)
      sum += rec.Bins["value"].(int)
    }
    fmt.Printf("Found sum for %s of %d\n", res.Record.Bins["name"], sum)
  }
```

However, when I rewrite it to do the scan first and the gets later, there's no trouble at all:

```
  recs := make(map[string]int)
  recordset, _ := AerospikeClient.ScanAll(nil, "dimensions", "headers")
  for res := range recordset.Results() {
    if res.Err != nil {
      fmt.Printf("During new scan: %s\n", res.Err.Error())
      continue
    }
    recs[res.Record.Bins["name"].(string)] = res.Record.Bins["itemcount"].(int)
  }

  for name, count := range recs {
    sum := 0
    for i := 0; i < count; i++ {
      key := fmt.Sprintf("item%d", i)
      itemKey, _ := aerospike.NewKey("dimensions", "items", key)
      rec, _ := AerospikeClient.Get(nil, itemKey)
      sum += rec.Bins["value"].(int)
    }
    fmt.Printf("Found sum for %s of %d\n", name, sum)
  }
```

Is there any expected reason why this might be happening?

I'm using the client at `d5e1682c`, server side is `community-3.10.1-ubuntu16.04`.

**Comment by khaf** [comment] 2016-12-15 19:03
No there is no expected reason. What type of data do you have inside the set? (simple bins? Maps, lists?)

This is not easy to reproduce. I populated a set and changed the bin names, and this didn't happen.

Do you think you can give us an snippet that also populates the data for your code snippet?

**Comment by khaf** [comment] 2016-12-17 13:36
I haven't been able to reproduce this issue. Is the following snippet a good representation of your code:

```go
package main

import (
	"flag"
	"fmt"
	"log"
	"runtime"
	"strconv"
	"sync"

	as "github.com/aerospike/aerospike-client-go"
)

var Host = flag.String("h", "127.0.0.1", "Aerospike server seed hostnames or IP addresses")
var Port = flag.Int("p", 3000, "Aerospike server seed hostname or IP address port number.")
var Namespace = flag.String("n", "test", "Aerospike namespace.")
var Set1 = flag.String("s1", "headers", "Headers set name.")
var Set2 = flag.String("s2", "items", "Items set name.")
var initdb = flag.Bool("i", false, "Write all keys to the db first. Only one run is necessary.")
var concurrency = flag.Int("c", 8, "Concurrency level.")
var recCount = flag.Int("r", 1e4, "Record Count.")

var wg sync.WaitGroup

func main() {
	runtime.GOMAXPROCS(runtime.NumCPU())
	flag.Parse()

	// connect to the host
	clientPolicy := as.NewClientPolicy()
	client, err := as.NewClientWithPolicy(clientPolicy, *Host, *Port)
	if err != nil {
		log.Fatalln(err.Error())
	}

	if *initdb {
		log.Println("Writing records to the db...")
		initDB(client)
		log.Println("Writing records to the db done.")
	}

	wg.Add(*concurrency)
	for i := 0; i < *concurrency; i++ {
		go scan(i, client)
	}

	wg.Wait()
}

func initDB(client *as.Client) {
	recordset, _ := client.ScanAll(nil, *Namespace, *Set1)
	for res := range recordset.Results() {
		if res.Err == nil {
			client.Delete(nil, res.Record.Key)
		}
	}

	recordset, _ = client.ScanAll(nil, *Namespace, *Set2)
	for res := range recordset.Results() {
		if res.Err == nil {
			client.Delete(nil, res.Record.Key)
		}
	}

	for i := 0; i < *recCount/10; i++ {
		key, _ := as.NewKey(*Namespace, *Set1, i)

		client.Put(nil, key, as.BinMap{
			"itemcount": i,
			"name":      "name" + strconv.Itoa(i),
		})
	}

	for i := 0; i < *recCount; i++ {
		key, _ := as.NewKey(*Namespace, *Set2, "item"+strconv.Itoa(i))
		client.Put(nil, key, as.BinMap{
			"value": 1,
		})
	}
}

func scan(id int, client *as.Client) {
	defer wg.Done()

	recordset, _ := client.ScanAll(nil, *Namespace, *Set1)
	for res := range recordset.Results() {
		if res.Err != nil {
			log.Printf("During scan: %s\n", res.Err.Error())
			continue
		}
		sum := 0
		for i := 0; i < res.Record.Bins["itemcount"].(int); i++ {
			key := fmt.Sprintf("item%d", i)
			itemKey, _ := as.NewKey(*Namespace, *Set2, key)
			rec, _ := client.Get(nil, itemKey)
			sum += rec.Bins["value"].(int)
		}
		log.Printf("%d: Found sum for %s of %d\n", id, res.Record.Bins["name"], sum)
	}
}
```

**Comment by allenluce** [comment] 2016-12-20 03:56
That code snippet doesn't have an extensive loop of gets within the the `ScanAll()`. I think that's critical to triggering the problem. My production code can loop 2000+ times within a single scan step.

A few attempts at constructing a reliable repro went nowhere so I instead bisected the server code. That fingers [a particular commit](https://github.com/aerospike/aerospike-server/commit/a227c9087dff7dd354e3619737ecfad7bfb06ff4) as the culprit.

My code fails with the weird errors on the [current master](https://github.com/aerospike/aerospike-server/commit/7d8133481bbca2d18276d362d3e3d092cf6ba500). If I change the value of [`CF_SOCKET_TIMEOUT` in `cf/include/socket.h`](https://github.com/aerospike/aerospike-server/blob/master/cf/include/socket.h#L37) from 10000 to -1, my code runs with no errors.

I translated my code into NodeJS and it was able to run fine without the `CF_SOCKET_TIMEOUT` change. I'm not sure why this issue affects the Go client in particular.

**Comment by khaf** [comment] 2016-12-20 15:55
This seems like you keep the scan waiting, and the connection goes stale from the server-side and released.

There was a minor bug that the client wouldn't return the error after the server would drop the connection, and as a result:
1. You wouldn't notice the error
2. The connection would be reused in the pool and the next command would read the stale data from the scan.

That bug is fixed, so this specific issue will not occur again, but you need to handle the problem of the server dropping your scan connections.

**Comment by allenluce** [comment] 2016-12-20 17:17
That made some kind of difference.  I did a couple runs this morning with 499adae. The first threw several errors:

```
EOF
Invalid Message Header: Expected version to be 2, but got 22
EOF
Server error
Server error
Invalid Message Header: Expected version to be 2, but got 22
EOF
Generation error
Generation error
Invalid Message Header: Expected version to be 2, but got 22
Error code (118) not available yet - please file an issue on github.
Error code (118) not available yet - please file an issue on github.
EOF
EOF
Generation error
Generation error
Server error
```

The "Invalid Message Header" messages came from the `AerospikeClient.Get()` calls within the scan loop.  All the rest are from `res.Err` (line 3 in my first post's first example). It's not clear to me how recovery from these should happen.

The second run gave me these errors, all from `res.Err`:

```
EOF
Invalid Message Header: Expected version to be 2, but got 22
EOF
```

And then a crash (after about 370 iterations of the scan loop):

```
panic: runtime error: slice bounds out of range

goroutine 12 [running]:
panic(0x678360, 0xc42000c150)
        /home/aluce/.gvm/gos/go1.7.3/src/runtime/panic.go:500 +0x1a1
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseKey(0xc420076dc0, 0x7073, 0x400, 0x14, 0xc400100000)
        /home/aluce/.gvm/pkgsets/go1.7.3/global/src/github.com/aerospike/aerospike-client-go/batch_command.go:139 +0x2b5
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseRecordResults(0xc420076dc0, 0x7e86c0, 0xc420076dc0, 0x23, 0x203000000000000, 0x0, 0x0)
        /home/aluce/.gvm/pkgsets/go1.7.3/global/src/github.com/aerospike/aerospike-client-go/batch_command.go:241 +0x1c9
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseResult(0xc420076dc0, 0x7e86c0, 0xc420076dc0, 0xc4201685b0, 0x0, 0x4e)
        /home/aluce/.gvm/pkgsets/go1.7.3/global/src/github.com/aerospike/aerospike-client-go/batch_command.go:105 +0x145
github.com/aerospike/aerospike-client-go.(*scanCommand).parseResult(0xc420076dc0, 0x7e86c0, 0xc420076dc0, 0xc4201685b0, 0x4e, 0x0)
        /home/aluce/.gvm/pkgsets/go1.7.3/global/src/github.com/aerospike/aerospike-client-go/scan_command.go:61 +0x48
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc420076dc0, 0x7e86c0, 0xc420076dc0, 0xc420076dc0, 0xc42000ab00)
        /home/aluce/.gvm/pkgsets/go1.7.3/global/src/github.com/aerospike/aerospike-client-go/command.go:1261 +0x4da
github.com/aerospike/aerospike-client-go.(*scanCommand).Execute(0xc420076dc0, 0x0, 0x0)
        /home/aluce/.gvm/pkgsets/go1.7.3/global/src/github.com/aerospike/aerospike-client-go/scan_command.go:66 +0x7f
github.com/aerospike/aerospike-client-go.(*Client).scanNode(0xc4200159e0, 0xc420013720, 0xc4200acb60, 0xc420055180, 0x6bc3e2, 0xa, 0x6bba66, 0x8, 0xd15bd5c244167e0a, 0x0, ...)
        /home/aluce/.gvm/pkgsets/go1.7.3/global/src/github.com/aerospike/aerospike-client-go/client.go:461 +0x112
github.com/aerospike/aerospike-client-go.(*Client).ScanAll.func1(0xc4200159e0, 0xc420013720, 0xc420055180, 0x6bc3e2, 0xa, 0x6bba66, 0x8, 0xd15bd5c244167e0a, 0x0, 0x0, ...)
        /home/aluce/.gvm/pkgsets/go1.7.3/global/src/github.com/aerospike/aerospike-client-go/client.go:416 +0xc3
created by github.com/aerospike/aerospike-client-go.(*Client).ScanAll
        /home/aluce/.gvm/pkgsets/go1.7.3/global/src/github.com/aerospike/aerospike-client-go/client.go:419 +0x24b
exit status 2
```

**Comment by khaf** [comment] 2016-12-22 20:38
Should be fixed by the latest commits in the master. Let me know how it goes.

**Comment by allenluce** [comment] 2016-12-22 23:34
Now I'm getting more understandable error messages:

```
Requested to read 22 bytes, but 12 was read. (EOF)
Requested to read 22 bytes, but 12 was read. (EOF)
Requested to read 11 bytes, but 9 was read. (EOF)
Requested to read 11 bytes, but 9 was read. (EOF)
Requested to read 30 bytes, but 20 was read. (EOF)
```

While it's not particularly indicative of the problem (i.e. the scan is taking too long), at least it's not as confusing as the original messages.

FYI, I made an issue on the server side, https://github.com/aerospike/aerospike-server/issues/165.

**Comment by khaf** [comment] 2016-12-23 08:58
This is as intended. What's happening is:

1. You ask for scan, and the server fills up a buffer and sends it your way. Since in your case the number of records is high (or their content is big enough), there are more than one buffer to send, so the server is blocked waiting for you to read the content off the socket.
2. The client library reads part of the buffer, parses the record and puts it on the records channel for you to read, and does this until the read channel is filled and then blocks.
3. You start issuing gets to the server, which seemingly collectively take more than 10 seconds.
4. The server thinks the connection has become stale, and drops it after 10 seconds of inactivity to free up resources, during which you are still working on the first batch of records sent.

The easiest (and memory hungry) way of avoiding this is to increase the `RecordQueueSize` in scan policy and adding to the concurrency of the sub-total calculation.

**Comment by khaf** [comment] 2016-12-23 16:46
I'm going to go ahead and close this issue. Feel free to reopen it or file a new issue.

**Closed by khaf** 2016-12-23 16:46 UTC
