### ISSUE TITLE
Scan Partition/Pagination

### ISSUE THREAD

**Issue by hsdfat** [aerospike/aerospike-client-go#428] opened 2024-04-21 11:34 UTC
Hi

I want to scan my set by partitions, but when I using parameter Maxrecords = 10. The returned result is only 10 and with only one page although have more records in database

I following the doc: [PI query with pagination](https://aerospike.com/developer/client/usage/queries/basic/primary?client=go#pagination)

I using Client v6 and Server v5.5

Can anyone explain?

```
scanPolicy := aerospike.NewScabPolicy()
scanPolicy.MaxRecords = 10;
partitionFilter := aerospike.NewPartitionFilterAll()
recordSet, err := client.ScanPartitions(scanPolicy, partitionFilter, MY_NS, MY_SET)
if err != nil {
    log.Fatal(err)
}

// Get the results
page := 0
for !partitionFilter.IsDone() {
    count := 0
    for records := range recordSet.Results() {
        if records != nil { 
            // Do something
            count ++
        }
    }
    page++
    recordSet, err = client.ScanPartitions(scanPolicy, partitionFilter, MY_NS, MY_SET)
    if err != nil {
       log.Fatal(err)
    }
}

recordSet.Close()
```

**Comment by khaf** [comment] 2024-04-21 22:30
I cannot reproduce the issue. This is the code I used (essentially your own), on servers v5.5, v6.4 and v7.0, and Go client v6.15.1 and v7.1.0:

```go
package main

import (
	"log"
	"strconv"
	"strings"
	"time"

	as "github.com/aerospike/aerospike-client-go/v6"
)

const (
	ns  = "test"
	set = "test"
)

func main() {

	policy := as.NewClientPolicy()
	policy.Timeout = 5 * time.Second
	client, err := as.NewClientWithPolicyAndHost(policy, as.NewHost("172.17.0.2", 3000))
	if err != nil {
		log.Panicf("failed to connect (%s)", err)
	}

	initDB(client)

	scanPolicy := as.NewScanPolicy()
	scanPolicy.MaxRecords = 10
	partitionFilter := as.NewPartitionFilterAll()
	recordSet, err := client.ScanPartitions(scanPolicy, partitionFilter, ns, set)
	if err != nil {
		log.Fatal(err)
	}

	m := map[int]struct{}{}

	// Get the results
	page := 0
	for !partitionFilter.IsDone() {
		count := 0
		for records := range recordSet.Results() {
			if records != nil {
				// Do something
				count++
				m[records.Record.Bins["itemcount"].(int)] = struct{}{}
			}
		}
		page++
		log.Printf("page: %d, count: %d\r", page, count)
		recordSet, err = client.ScanPartitions(scanPolicy, partitionFilter, ns, set)
		if err != nil {
			log.Fatal(err)
		}
	}

	log.Println("total unique records returned:", len(m))
	recordSet.Close()
}

func initDB(client *as.Client) {
	err := client.Truncate(nil, ns, set, nil)
	if err != nil {
		log.Fatalln(err.Error())
	}

	time.Sleep(5 * time.Second)

	filler := strings.Repeat("a", 100)
	for i := 0; i < 10000; i++ {
		key, _ := as.NewKey(ns, set, i)

		err := client.Put(nil, key, as.BinMap{
			"itemcount": i,
			"name":      "name" + strconv.Itoa(i),
			"filler":    filler,
		})
		if err != nil {
			log.Fatalln(err.Error())
		}
	}
}
```

**Comment by khaf** [comment] 2024-05-08 23:14
Closing this ticket. Feel free to reopen if the issue persists.

**Closed as completed by khaf** 2024-05-08 23:14 UTC
Labels: invalid
