### ISSUE TITLE
DropIndex function does not work. 

### ISSUE THREAD

**Issue by sacheendra** [aerospike/aerospike-client-go#44] opened 2015-01-11 10:52 UTC
The DropIndex function completes without any error, but when I try to create an Index with the same name, an Index already exists error is returned.

**Comment by khaf** [comment] 2015-01-12 10:41
I can't reproduce this in a few different configurations that I usually test. Would you provide more information regarding:

- If your client is the latest in master (or your fork is updated)
- Which server version are you working with, and the cluster configuration (number of nodes, namespaces config, etc.)
- A snippet of the code you are using that can reproduce this bug.

**Comment by sacheendra** [comment] 2015-01-12 11:28
Yes, my client is the latest in master. 
I am using aerospike from the official aerospike docker image "aerospike/aerospike-server".
The configuration is single node with single namespace persisting to disk and udf cache disabled. 

The problem appears not to be in the client but in the server. 
Uploading a lua udf with a function defined as both local and global seems to cause problems with the server. 
The above problem with indexes not being dropped is caused due to the server being stuck in some kind of loop due to loading the above mentioned kind of udf.

**Comment by khaf** [comment] 2015-01-12 16:00
Thank you for letting me know. Would you please report it to the server repo so that it is taken care of for the next release?

I'll close this ticket for now. Don't hesitate to follow up or report other issues.

**Closed by khaf** 2015-01-12 16:00 UTC
