### ISSUE TITLE
batch-index protocol for batch operations

### ISSUE THREAD

**Issue by clusc** [aerospike/aerospike-client-go#214] opened 2017-10-27 03:32 UTC
Hi,

We are just being informed today that the go client is still using the old batch-direct protocol for batch operations, while debugging why the metrics are missing in our dashboard. Is there any plan to support it? 

Eric

**Comment by khaf** [comment] 2017-10-28 13:30
I'm working on it at the moment. Hopefully will release it next week.

**Comment by clusc** [comment] 2017-10-28 17:01
Awesome, keep us posted.

**Comment by khaf** [comment] 2017-11-29 14:52
Released with Delay. Had to debug a particularly nasty bug.

**Closed by khaf** 2017-11-29 14:52 UTC

**Comment by clusc** [comment] 2017-11-29 21:30
Thanks, we are upgrading now.

**Comment by clusc** [comment] 2017-11-30 00:29
@khaf We just found out that the new protocol doesn't return the key's set name(`rec.Key.SetName()` is nil), even if we set the sendKey write policy to true already(we always do). Setting `BatchPolicy.UserBatchDirect = true` returns the setname successfully. Is this the intended behavior? We have some logic that relies on setname() to be present unfortunately.

**Comment by khaf** [comment] 2017-11-30 21:10
While that behavior is intended and as designed, I've introduced a workaround to support your use-case. Update your code to the latest master.

Let me know how it goes.

**Comment by clusc** [comment] 2017-12-01 01:11
@khaf confirmed the latest master works, thanks a lot! Can we have a new release anytime soon?

**Comment by khaf** [comment] 2017-12-01 15:58
Anything in the master is reliable and well tested. Releases are just milestones we designate a version number to.
