### ISSUE TITLE
EOF on PutObject

### ISSUE THREAD

**Issue by cgebe** [aerospike/aerospike-client-go#258] opened 2019-03-28 12:07 UTC
Since i upgraded to 2.0.0, i occasionally get EOF errors reported when calling `client.PutObject(nil, key, obj)`. Looks like the server closes the connection and the client does not handle it correctly. Or the server does not act properly? Server version: `4.3.0.7`

I have not yet investigated further.

**Comment by khaf** [comment] 2019-03-28 13:56
Thanks for your report. Are you using any of Batch/Query/Scan/ExecuteUDF?

How prevalent is the EOF?

**Comment by cgebe** [comment] 2019-03-28 16:30
This is how i call it:
```
func (m *Memory) InsertPack(id string, pack model.Pack) error {
	key, err := aerospike.NewKey(m.Namespace, id)
	if err != nil {
		panic(err)
	}
	return m.Client.PutObject(nil, key, pack)
}
```

Important to mention: The method is executed in parallel by ~400 goroutines regularly at the same point in time (all are triggered simultaneously). I guess, it is an issue with concurrency. From these ~400 calls about 4-5% fail. Catching the error and retrying is my current solution. Every call goes through eventually.

**Comment by cgebe** [comment] 2019-03-29 10:45
Downgraded to 1.39 again, since the error occurred too often. Interestingly, the error occurred repeatedly in the same goroutines instead of equally distributed across all workers.

**Comment by khaf** [comment] 2019-03-29 11:00
Interesting thing is that I can't reproduce the problem easily. It may have something to do with the latencies involved in your environment. Are you by any chance running in a cloud environment?

**Comment by cgebe** [comment] 2019-03-29 12:55
Yes, i can confirm that this issue only occurring in kubernetes setup and not locally. I run aerospike on a 4 machine cluster with 20GB memory each (+storage device HDD - data in memory). Have not yet upgraded the server version.

**Comment by xqinghu** [comment] 2019-04-16 06:28
rt

**Comment by khaf** [comment] 2019-04-17 09:58
Any new findings regarding this issue? `io.EOF` normally happens when the server closes a connection. Since the server does not close connections for Read and Write transactions, we need to find out why that happens. Do you see anything unusual in server logs?

**Comment by cgebe** [comment] 2019-04-17 16:17
Unfortunately, I cannot give further information, since i downgraded the client version. If there is a chance to test again, i will report back.

**Comment by khaf** [comment] 2019-05-22 14:59
I believe that the latest releases have resolved this issue. I'll close this ticket, but feel free to either reopen or file a new one.

**Closed by khaf** 2019-05-22 14:59 UTC
